### Products Index Action
GET http://localhost:3000/products.json

### Products Show Action
GET http://localhost:3000/products/1.json

### Products Create Action
POST http://localhost:3000/products.json
Content-Type: application/json

{
"name": "pants",
"price": "15", 
"image_url": "pants.picture.jpg",
"description": "pants description"
}

### Prodcut Update Action
PATCH http://localhost:3000/products/9.json
Content-Type: application/json

{
"name": "Spongebob Pants",
"price": "20", 
"image_url": "sponge_pants",
"description": "who lives in a pineapple under the sea"
}

### Product Destroy Action
DELETE http://localhost:3000/products/6.json


### Suppliers
### Index Action
GET http://localhost:3000/suppliers.json

### Show Action
GET http://localhost:3000/suppliers/1.json

### Create Action
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
"name": "amazon",
"price": "1", 
"image_url": "pants.picture.jpg",
"description": "pants description"
}

### Prodcut Update Action
PATCH http://localhost:3000/products/9.json
Content-Type: application/json

{
"name": "Spongebob Pants",
"price": "20", 
"image_url": "sponge_pants",
"description": "who lives in a pineapple under the sea"
}

### Product Destroy Action
DELETE http://localhost:3000/products/6.json


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@test.com",
  "password": "password",
  "password_confirmation": "password"
}