@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI4MzYxNDV9.bkjJPTrEseEokhR-EP29l7GQATLeJX0_B7sUiIFWxfo

### Products Index Action
GET http://localhost:3000/products.json?category=absorbent

### Products Show Action
GET http://localhost:3000/products/1.json

### Products Create Action
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"name": "bracelet",
"price": "40", 
"image_url": "bracelet.picture.jpg",
"description": "bracelet description"
}

### Prodcut Update Action
PATCH http://localhost:3000/products/9.json
Content-Type: application/json

{
"name": "Spongebob Pants",
"price": "20", 
"image_url": "sponge_pants",
"description": "who lives in a pineapple under the sea"
}

### Product Destroy Action
DELETE http://localhost:3000/products/6.json


### Suppliers
### Index Action
GET http://localhost:3000/suppliers.json

### Show Action
GET http://localhost:3000/suppliers/1.json

### Create Action
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
"name": "amazon",
"price": "1", 
"image_url": "pants.picture.jpg",
"description": "pants description"
}

### Prodcut Update Action
PATCH http://localhost:3000/products/9.json
Content-Type: application/json

{
"name": "Spongebob Pants",
"price": "20", 
"image_url": "sponge_pants",
"description": "who lives in a pineapple under the sea"
}

### Product Destroy Action
DELETE http://localhost:3000/products/6.json


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "user1@test.com",
  "password": "password"
}

### ??
# POST http://localhost:3000/photos.json
# Authorization: Bearer yJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI3NDQwNjB9.HYaw0fKkXJYW8pdGbWM5uiJzWEQ4tJw3Btazvw6yw3o
# Content-Type: application/json

# {
#   "name": "Test name",
#   "width": 640,
#   "height": 480
# }

### Orders Create Action
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI4MjY3MjF9.LD8Gn5i-m1ajyrb7WNgz-SUL_JrK-Yx-Xtw0n3PRgP4
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 3
}

### Orders Show Action
GET http://localhost:3000/orders/1.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI4MjY3MjF9.LD8Gn5i-m1ajyrb7WNgz-SUL_JrK-Yx-Xtw0n3PRgP4

### Orders Index Action
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI4MjY3MjF9.LD8Gn5i-m1ajyrb7WNgz-SUL_JrK-Yx-Xtw0n3PRgP4